### ISSUE TITLE
Falscher Datentyp

### ISSUE THREAD

**Issue by DerDoubleD** [klein0r/ioBroker.comfoairq#15] opened 2021-08-13 23:00 UTC
im Log erscheinen sehr viele dieser Meldungen...
`
info:  comfoairq.0 (2387) State value to set for  "comfoairq.0.sensor.powerCurrent" has to be type "string" but received  type "number"

info:  comfoairq.0 (2387) State value to set for  "comfoairq.0.sensor.fanExhaustSpeed" has to be type "string" but  received type "number"

info:  comfoairq.0 (2387) State value to set for  "comfoairq.0.sensor.fanExhaustFlow" has to be type "string" but received  type "number"

info:  comfoairq.0 (2387) State value to set for  "comfoairq.0.sensor.fanExhaustSpeed" has to be type "string" but  received type "number"

info:  comfoairq.0 (2387) State value to set for  "comfoairq.0.sensor.fanExhaustFlow" has to be type "string" but received  type "number"
`

**Comment by Revilo91** [comment] 2021-08-17 15:22
Ist #12 nicht der selbe Issue?

Kleine HIlfe für die Logdatei: 

![image](https://user-images.githubusercontent.com/39066472/129754066-533da96a-8e68-43ce-92f3-5454641eaf0d.png)
Unter Instanzen auf comfoair gehen und hier auf Warnung stellen, dann wird der Log nicht so zugeschüttet

Lg
Revilo

**Comment by klein0r** [comment] 2021-08-17 18:23
Duplicate of #12

**Closed by klein0r** 2021-08-17 18:23 UTC
